repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.5.0
      hooks:
          - id: check-yaml
          - id: end-of-file-fixer
          - id: trailing-whitespace
          - id: check-ast
          - id: check-byte-order-marker
            exclude: tests/data/toc-ntk-sample/.*
          - id: check-xml
    - repo: https://github.com/psf/black
      rev: 20.8b1
      hooks:
          - id: black
